selenium-chrome:
  image: selenium/standalone-chrome:2.46.0
test-chrome:
  build: .
  volumes:
    - .:/app
  command: sh -c 'sleep 1; wdio wdio.conf.js --host selenium-chrome --port 4444'
  links:
    - selenium-chrome
  working_dir: /app
  environment:
    WDIO_BROWSER_NAME: 'chrome'

phantomjs:
  image: cmfatih/phantomjs
  ports:
    - 8910
  entrypoint: phantomjs
  command: "--webdriver=8910"
test-phantomjs:
  build: .
  volumes:
    - .:/app
  command: sh -c 'sleep 1; wdio wdio.conf.js --host phantomjs --port 8910'
  links:
    - phantomjs
  working_dir: /app
  environment:
    WDIO_BROWSER_NAME: 'phantomjs'


selenium-firefox:
  image: selenium/standalone-firefox:2.46.0
test-firefox:
  build: .
  volumes:
    - .:/app
  command: sh -c 'sleep 1; wdio wdio.conf.js --host selenium-firefox --port 4444'
  links:
    - selenium-firefox
  working_dir: /app
  environment:
    WDIO_BROWSER_NAME: 'firefox'
